import type { Section, Subsection } from "./types";

export const SECTION_LABEL_KO: Record<Section, string> = {
  politics: "정치",
  business: "경제",
  industry: "산업",
  society: "사회",
  local: "전국",
  world: "세계",
  culture: "문화",
  sports: "스포츠",
  health: "건강",
  entertainment: "연예",
};

export const SUBSECTION_LABEL_KO: Record<Subsection, string> = {
  "presidential-office": "대통령실/총리실",
  assembly: "국회/정당",
  diplomacy: "외교",
  defense: "국방",
  finance: "금융",
  "real-estate": "부동산",
  "jobs-startup": "취업/창업",
  consumer: "소비자",
  electronics: "전기전자",
  "heavy-chem": "중화학",
  automobile: "자동차",
  construction: "건설",
  "energy-resources": "에너지/자원",
  "tech-science": "IT/과학",
  game: "게임",
  "retail-service": "유통/서비스",
  "smb-venture": "중기/벤처",
  "bio-health": "바이오/헬스",
  "agri-livestock": "농림축산",
  "marine-fishery": "해양수산",
  // Local (extended)
  gyeonggi: "경기",
  ulsan: "울산",
  gyeongnam: "경남",
  "daegu-gyeongbuk": "대구/경북",
  "gwangju-jeonnam": "광주/전남",
  jeonbuk: "전북",
  "daejeon-chungnam-sejong": "대전/충남/세종",
  chungbuk: "충북",
  gangwon: "강원",
  gwangju: "광주",
  busan: "부산",
  incheon: "인천",
  daegu: "대구",
  jeju: "제주",
  "us-na": "미국/북미",
  cn: "중국",
  jp: "일본",
  "asia-au": "아시아/호주",
  eu: "유럽",
  latam: "중남미",
  mea: "중동/아프리카",
  igo: "국제기구",
  incident: "사건/사고",
  "court-prosecution": "법원/검찰",
  education: "교육",
  "welfare-labor": "복지/노동",
  "environment-climate": "환경/기후변화",
  "women-children": "여성/아동",
  "overseas-korean": "재외동포",
  multicultural: "다문화",
  "books-lit": "책/문학",
  "comics-webtoon": "만화/웹툰",
  religion: "종교",
  "performance-exhibition": "공연/전시",
  "academia-heritage": "학술/문화재",
  media: "미디어",
  "travel-leisure": "여행/레저",
  life: "생활",
  broadcast: "방송",
  movie: "영화",
  kpop: "가요",
  "global-ent": "해외연예",
  baseball: "야구",
  football: "축구",
  "basketball-volleyball": "농구/배구",
  golf: "골프",
  // Health
  "health-note": "헬스노트",
  "weekly-health": "위클리 건강",
};

export function sectionLabelKo(section: Section): string {
  return SECTION_LABEL_KO[section] ?? section;
}

export function subsectionLabelKo(sub: Subsection): string {
  return SUBSECTION_LABEL_KO[sub] ?? sub;
}
